# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerGiven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcerciseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('answer', models.CharField(max_length=32)),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_finding.Excercise')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='excercisestate',
            name='current_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='word_finding.Question'),
        ),
        migrations.AddField(
            model_name='excercisestate',
            name='excercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_finding.Excercise'),
        ),
        migrations.AddField(
            model_name='excercisestate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_finding.User'),
        ),
        migrations.AddField(
            model_name='answergiven',
            name='excercise_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_finding.ExcerciseState'),
        ),
        migrations.AddField(
            model_name='answergiven',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_finding.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('excercise', 'question')]),
        ),
    ]
