# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_finding', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excercise',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='ExcerciseState',
            new_name='ExerciseState',
        ),
        migrations.RenameField(
            model_name='answergiven',
            old_name='excercise_state',
            new_name='exercise_state',
        ),
        migrations.RenameField(
            model_name='exercisestate',
            old_name='excercise',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='excercise',
            new_name='exercise',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('exercise', 'question')]),
        ),
    ]
