# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_finding', '0002_auto_20171220_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
    ]
