# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_finding', '0003_auto_20171220_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
