# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_finding', '0004_auto_20171220_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
