# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_finding', '0007_auto_20171221_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='raw_question',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('exercise', 'question')]),
        ),
    ]
